<?php ob_start() ?>

<div class="container mt-3">
    
    <div class="d-flex justify-content-around">
        <div class="card" style="width:400px">
            <h2 class="text-center">Chambre 1</h2>
            <img class="card-img-top" src="photo/image1.jpg" alt="image1" style="width:100%">

            <div class="card-body text-center">
                <a href="?action=get&numChambre=11" class="btn btn-primary text-center ">Détail</a>
            </div>
        </div>

        <div class="card" style="width:400px">
            <h2 class="text-center">Chambre 2</h2>
            <img class="card-img-top" src="photo/image3.jpg" alt="image1" style="width:100%">

            <div class="card-body text-center">
            
                <a href="?action=gets&numChambre=12" class="btn btn-primary text-center ">Détail</a>
            
                <?php if ( isset($_SESSION['utilisateur']) && unserialize($_SESSION['utilisateur'])->getRole() == "admin"  ) : ?> 
                <a href="?action=gets&numChambre=12" class="btn btn-primary text-center ">Détail</a>
                <a href="?action=delete" class="btn btn-primary text-center ">Supprimer</a>
                <a href="?update=modifier" class="btn btn-primary text-center ">Modifier</a>
                <?php endif; ?>
            
            </div>
        </div>
    </div>
    
</div>
<?php $content = ob_get_clean();

    include "vues/template.phtml";