<?php ob_start() ?>

   
    <div class="container mt-3">
        <div class="row">
            
                <div class="card col" style="width:400px" >
                    <h2 class="text-center fs-1 fw-bold">Chambre 1</h2>
                    <img class="card-img-top px-3" src="photo/image1.jpg" alt="image1" style="width:100%">

                    <div class="card-body bg-dark mx-3 text-center">
                        <a href="?action=get&numChambre=11" class="btn btn-danger text-center d-block my-3 rounded-pill">Détail</a><br>

                        <?php if ( isset($_SESSION['utilisateur']) && unserialize($_SESSION['utilisateur'])->getRole() == "admin"  ) : ?> 
                        <a href="?action=delete" class="btn btn-danger text-center d-block my-3 rounded-pill">Modification</a><br>
                        <a href="?update=modifier" class="btn btn-danger text-center d-block my-3 rounded-pill ">Supprimer</a>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="card col" style="width:400px">
                    <h2 class="text-center fs-1 fw-bold">Chambre 2</h2>
                    <img class="card-img-top px-3" src="photo/image3.jpg" alt="image1" style="width:100%">

                    <div class="card-body bg-dark mx-3 text-center">
                    
                        <a href="?action=gets&numChambre=12" class="btn btn-danger text-center d-block my-3 rounded-pill">Détail</a><br>
                    
                        <?php if ( isset($_SESSION['utilisateur']) && unserialize($_SESSION['utilisateur'])->getRole() == "admin"  ) : ?> 
                        <a href="?action=delete" class="btn btn-danger text-center d-block my-3 rounded-pill">Modification</a><br>
                        <a href="?update=modifier" class="btn btn-danger text-center d-block my-3 rounded-pill">Supprimer</a>
                        <?php endif; ?>
                    
                    </div>
                </div>
               
        </div>
        
    </div>
<?php $content = ob_get_clean();

    include "vues/template.phtml";