<?php ob_start() ?>

   

    <!------------------------------------------------------------------- section about ---------------------------------------------------->

   <h2><a href=""> À PROPOS DE L'AUBERGE </a></h2>
    <hr class="line">
        <div class="main">
            <div class="container">
                <div class="imag"></div>
                <div class="text-container">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus ducimus tenetur quis amet eum consequatur numquam quasi vel laudantium blanditiis enim, distinctio saepe, cumque voluptate quas perspiciatis illo? Expedita voluptates aspernatur pariatur aliquam veniam soluta consectetur, modi blanditiis iste a accusantium harum repudiandae ipsa sequi placeat. Non cum inventore error. </p>
                </div>
            </div>
        </div>

     <!----------------------------------------------------------------- section menu -------------------------------------------------------->

    <section id="special" class="container-fluid">

<div class="heading text-center">
    <h2><a href=""> MENU DE L'AUBERGE </a></h2>
    <hr class="line">
</div>
        
        
<div class="card-container">
        
    <div class="card">
         <img src="photo/image1.jpg" alt="Menu burger">
        <h3>Chambre 1</h3>
        <p class="plat">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus ducimus tenetur quis amet eum consequatur numquam quasi vel laudantium blanditiis enim, distinctio saepe.</p>
        <a href="?action=get&numChambre=12" ><p class="prix">Détail</p></a>
    </div>
        
    <div class="card">
        <img src="photo/image2.jpg" alt="Menu pasta">
        <h3>Chambre 2</h3>
        <p class="plat">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus ducimus tenetur quis amet eum consequatur numquam quasi vel laudantium blanditiis enim, distinctio saepe.</p>
        <a href="?action=get&numChambre=11" ><p class="prix">Détail</p></a>
    </div>
        
    <div class="card">
        <img src="photo/image3.jpg" alt="Menu pizza">
        <h3>Chambre 3</h3>
        <p class="plat">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus ducimus tenetur quis amet eum consequatur numquam quasi vel laudantium blanditiis enim, distinctio saepe.</p>
        <a href="?action=get&numChambre=11" ><p class="prix">Détail</p></a>
    </div>
        
</div>
        
</section>   

        <!--------------------------------------------------- Carousel ------------------------------------------>
        <h2><a href=""> GALERIE </a></h2>
        <hr class="line">
        <div id="demo" class="carousel slide container-fluid" data-bs-ride="carousel">

        
            <!-- Indicators/dots -->
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
                <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
                <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
                <button type="button" data-bs-target="#demo" data-bs-slide-to="3"></button>
                <button type="button" data-bs-target="#demo" data-bs-slide-to="4"></button>
            </div>

            <!-- The slideshow/carousel -->
            <div class="carousel-inner">
                <div class="carousel-item active">
                <img src="photo/hotel1.jpg" alt="Los Angeles" class="d-block ">
                </div>

                <div class="carousel-item">
                <img src="photo/hotel2.jpg" alt="Chicago" class="d-block ">
                </div>

                <div class="carousel-item">
                <img src="photo/hotel3.jpg" alt="New York" class="d-block ">
                </div>

                <div class="carousel-item">
                <img src="photo/hotel4.jpg" alt="New York" class="d-block ">
                </div>

                <div class="carousel-item">
                <img src="photo/hotel5.jpg" alt="New York" class="d-block ">
                </div>

            </div>

            <!-- Left and right controls/icons -->
            <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
                <span class="carousel-control-next-icon"></span>
            </button>
        </div>


   <!-- <div class="container mt-3 ">
        <div class="row ">
            
                <div class="card col" style="width:400px" >
                    <h2 class="text-center fs-1 fw-bold">Chambre 1</h2>
                    <img class="card-img-top px-3" src="photo/image1.jpg" alt="image1" style="width:100%">

                    <div class="card-body bg-dark mx-3 text-center">
                        <a href="?action=get&numChambre=11" class="btn btn-danger text-center d-block my-3 rounded-pill">Détail</a><br>

                        <?php if (isset($_SESSION['utilisateur']) && unserialize($_SESSION['utilisateur'])->getRole() == "admin") : ?> 
                        <a href="?action=delete" class="btn btn-danger text-center d-block my-3 rounded-pill">Modification</a><br>
                        <a href="?update=modifier" class="btn btn-danger text-center d-block my-3 rounded-pill ">Supprimer</a>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="card col" style="width:400px">
                    <h2 class="text-center fs-1 fw-bold">Chambre 2</h2>
                    <img class="card-img-top px-3" src="photo/image3.jpg" alt="image1" style="width:100%">

                    <div class="card-body bg-dark mx-3 text-center">
                    
                        <a href="?action=gets&numChambre=12" class="btn btn-danger text-center d-block my-3 rounded-pill">Détail</a><br>
                    
                        <?php if (isset($_SESSION['utilisateur']) && unserialize($_SESSION['utilisateur'])->getRole() == "admin") : ?> 
                        <a href="?action=delete" class="btn btn-danger text-center d-block my-3 rounded-pill">Modification</a><br>
                        <a href="?update=modifier" class="btn btn-danger text-center d-block my-3 rounded-pill">Supprimer</a>
                        <?php endif; ?>
                    
                    </div>
                </div>
               
        </div>
        
    </div> -->
<?php $content = ob_get_clean();

    include "vues/template.phtml";
