<?php ob_start(); ?>
     <h2 class="text-center">Connexion</h2>
    
     <form action="" method="post">

          <div class="form-group">
               <label for="">Login</label>
               <input type="text" name="login" value="pseudo" class="form-control">
          </div>

          <div class="form-group">
               <label for="">Mot de passd</label>
               <input type="password" name="mdp"  class="form-control">
          </div>

          <input type="submit" class="btn btn-success mt-2">
     </form>

<?php 

$content = ob_get_clean();

include "vues/template.phtml";