
<?php ob_start(); ?>
<div class="container card mx-auto d-block" style="width: 30%;">
    <form action="" method="post">
        <input type="hidden" name="numChambre" value="<?= $_GET['numChambre']?? 0 ?>">
        <div class="mb-3">
            <label for="nom" class="form-label">Nom :</label>
            <input type="text" class="form-control"  placeholder="Entrer votre nom" name="nom">
        </div>

        <div class="mb-3">
            <label for="prenom" class="form-label">Prenom :</label>
            <input type="text" class="form-control"  placeholder="Entrer votre prenom" name="prenom">
        </div>

        <div class="mb-3">
            <label for="tel" class="form-label">Tél :</label>
            <input type="tel" class="form-control" placeholder="01 23 45 67 89" name="tel" >
        </div>
      
        
        <div class="mb-3">
            <label for="" class="form-label">Date d'arrivée :</label>
            <input type="date" class="form-control"  name="dateA">
        </div>

        <div class="mb-3">
            <label for="" class="form-label">Date de départ:</label>
            <input type="date" class="form-control"   name="dateD">
        </div>
        
        <input type="submit"  class="btn btn-primary mb-3">
    </form> 
</div>

<?php $content = ob_get_clean();

include "vues/template.phtml";
