<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
     <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
     <link rel="stylesheet" href="css/style.css">
     <title>Hotel</title>
</head> 

<body>
    <header >

        <div class="bg-dark p-5 mb-5 text-white border border-0 border-bottom">
            <nav>
                <a href="." class="text-white"><h1 class="text-center fs-1 fw-bold">Bienvenue sur notre site</h1></a>
            </nav>
            
            <nav>
                <?php if ( empty($_SESSION['utilisateur']) ) : ?>
                    <a href="?action=connexion" class="text-white">Se connecter</a> 
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="?action=inscription" class="text-white " >Inscription</a>
                <?php else: ?>   
                    <a href="?action=ajouter">liste reservation</a>
                    <?php if (unserialize($_SESSION['utilisateur'])->getRole() == "admin"  ) : ?> 
                        <a href="?action=ajouter">Ajouter</a>
                    <?php endif; ?>
                    <div class="text-end">
                        <?= "Bonjour " . unserialize($_SESSION['utilisateur'])->getRole() ?>
                        <a href="?action=deconnexion">Déconnexion</a>
                    </div>
                <?php endif; ?>    
            </nav>
        </div>
       
        
        <div id="all_slider">
            <ul id="slider">
                <li class="slide"><img src="photo/image1.jpg"></li>
                <li class="slide"><img src="photo/image2.jpg"></li>
                <li class="slide"><img src="photo/image3.jpg"></li>
                <li class="slide"><img src="photo/image2.jpg"></li>
                <li class="slide"><img src="photo/image3.jpg"></li>
                
            </ul>
        </div>
        
        <div id="titre">
            <h3 class="fs-1 text-capitalize fw-bold">Apprendre à créer des sites web <br> en toute simplicité !</h3>
            <button type="button" name="button" class="btn-s">Nos services</button>
            <button type="button" name="button" class="btn-c">Contactez-nous</button>
        </div>
    </header>
    
    <?php if( isset($_SESSION['message']) ): ?>
        <div class="text-center bg-primary text-info p-3">
            <?= $_SESSION['message'] ?? '' ?>
        </div>
    <?php endif; ?>
    <main class="container-fluid mt-3 mb-5">
        <?= $content ?? "page vide" ?>
    </main>
    <footer class="bg-dark py-5  mb-0 mt-2">
        <div class="container">
            <p class="m-0 text-center text-white fs-1"> &copy; 2020 - 2021 - Hotel - M Wone <?= date("d/m/Y") ?></p>
        </div>
    </footer>
    <?php unset( $_SESSION['message'] ); ?>
</body> 

</html>   